#### general settings
name: Gauss
train_type: REG
gpu_ids: [2]


#### datasets
data:
  name: "simulated"
  n: 10000
  scenario: 6

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/BMLP_L3_S6/"
  save_checkpoint_freq: 5

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

model:
  name: MLP
  layer_type: Gauss

  n_blocks: 3

  prior:
    prior_mu: 0
    prior_sigma: 0.1
    posterior_mu_initial: [ 0, 0.01 ]
    posterior_rho_initial: [ -4, 0.01 ]

  in_channels: 1000
  out_channels: 1

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "BMLP"

  num_epochs: 100
  batch_size: 128

#### Logging
logging:
  mode: online # disabled
  tags: [
      "REG",
      "MLP",
      "Gaussian"
  ]