#### general settings
name: MFVI
train_type: linreg
gpu_ids: [2]


#### datasets
data:
  name: "simulated"
  n: 10000
  scenario: 6

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/MFVI_MLP_L3_S6/"
  save_checkpoint_freq: 5


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "BMLP"

  num_epochs: 100
  batch_size: 1024
  train_size: 1
  n_blocks: 3

  beta: 0.001
  prior_mu: 0
  prior_sigma: 0.01
  posterior_mu_initial: [0, 0.01]
  posterior_rho_initial: [-2.5, 0.01]

  in_channels: 1000
  out_channels: 1

  loss: "ELBO"
