#### general settings
name: RAD
train_type: REG
gpu_ids: [2]


#### datasets
data:
  name: "simulated"
  n: 10000
  scenario: 6

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/RAD_L3_S6/"
  save_checkpoint_freq: 5


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001  # Learning rate
  weight_decay: 0.001

#### Model Settings
model:
  name: MLP
  layer_type: RAD

  n_blocks: 3

  prior:
    prior_mu: 0
    prior_sigma: 0.1
    posterior_mu_initial: [ 0, 0.01 ]
    posterior_rho_initial: [ -4, 0.01 ]

  in_channels: 1000
  out_channels: 1


#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 100
  batch_size: 1024
  train_size: 1

#### Logging
logging:
  mode: online # disabled
  tags: [
      "REG",
      "MLP",
      "RAD"
  ]