#### general settings
name: MCD
train_type: OOD
eval_type: bnn
gpu_ids: [2]


#### datasets
data:
  in: "CIFAR10"
  ood: "SVHN"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/OOD/GAUSS_CIFAR10_SVHN"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

model:
  name: "LeNet"
  layer_type: MCD
  in_channels: 1
  out_channels: 10

  prior:
    prior_mu: 0
    prior_sigma: 0.01
    posterior_mu_initial: [0, 0.01]
    posterior_rho_initial: [-3, 0.01]

#### training settings: learning rate scheme, loss, optimizer
train:

  num_epochs: 100
  batch_size: 1024
  train_size: 1

  MCD: 0.15

  n_samples: 10

  beta: 0.005

#### Logging
logging:
  mode: online # disabled
  tags: [
      "CIFAR10",
      "SVHN",
      "OOD",
      "LeNet",
      "GAUSS"
    ]