#### general settings
name: DE_Freq
train_type: CLS
gpu_ids: [2]

#### datasets
data:
  name: "ImageNet"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/DE_AlexNet_ImageNet/"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### Model settings
model:
  name: "AlexNet"
  layer_type: Freq
  n_models: 5

  in_channels: 3
  out_channels: 100

#### training settings: learning rate scheme, loss, optimizer
train:

  num_epochs: 500
  batch_size: 128
  train_size: 1

  loss: "CE"

#### Logging
logging:
  mode: online # disabled
  tags: [
      "ImageNet",
      "CLS",
      "AlexNet",
      "Frequentist",
      "DeepEnsemble"
    ]