#### general settings
name: MFVI
train_type: CLS
gpu_ids: [2]


#### datasets
data:
  name: "ImageNet"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/MFVIAlexNet_ImageNet/"
  save_checkpoint_freq: 5


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### Model Settings
model:
  name: AlexNet
  layer_type: MFVI

  prior:
    prior_mu: 0
    prior_sigma: 0.01
    posterior_mu_initial: [0, 0.01]
    posterior_rho_initial: [-3, 0.01]

  in_channels: 3
  out_channels: 100


#### training settings: learning rate scheme, loss, optimizer
train:

  num_epochs: 500
  batch_size: 128
  beta: 0.001
  train_size: 1

#### Logging
logging:
  mode: online # disabled
  tags: [
      "ImageNet",
      "CLS",
      "AlexNet",
      "MFVI"
    ]