#### general settings
name: R2D2M
train_type: CLS
eval_type: bnn
gpu_ids: [2]


#### datasets
data:
  name: "ImageNet"
  image_size: 64
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/R2D2_AlexNet_ImageNet/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001  # Learning rate
  weight_decay: 0.001

#### Model Settings
model:
  name: "AlexNet"
  layer_type: R2D2M

  prior:
    r2d2_scale:
    prior_phi_prob: 0.6
    prior_psi_shape: 0.5
    beta_rho_scale: [-4.5, 0.1]
    bias_rho_scale: [-4.5, 0.1]
    weight_xi_shape: 0.3
    weight_omega_shape: 0.5

  in_channels: 3
  out_channels: 200

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 2000
  batch_size: 1024
  train_size: 1

  beta: 0.001

#### Logging
logging:
  mode: online # disabled
  tags: [
      "ImageNet",
      "CLS",
      "AlexNet",
      "R2D2",
      "Marginal",
    ]