#### general settings
name: BPN
train_type: bnn-horseshoe
eval_type: bnn
gpu_ids: [2]


#### datasets
data:
  name: "MNIST"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/HorseshoeSimpleCNN_MNIST/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "HorseshoeSimpleCNN"

  num_epochs: 1000
  batch_size: 128
  train_size: 1

  beta: 0.00001

  horseshoe_scale:
  global_cauchy_scale: 1.
  weight_cauchy_scale: 1.
  beta_rho_scale: -5.
  log_tau_mean:
  log_tau_rho_scale: -5.
  bias_rho_scale: -5.
  log_v_mean:
  log_v_rho_scale: -5.

  in_channels: 1
  out_channels: 10

  loss: "ELBO"
