#### general settings
name: BPN
train_type: bnn-r2d2
eval_type: bnn
gpu_ids: [2]


#### datasets
data:
  name: "FashionMNIST"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/R2D2LeNet_v2_FashionMNIST/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "R2D2LeNet"

  num_epochs: 2000
  batch_size: 1024
  train_size: 1

  beta: 0.00001

  r2d2_scale:
  prior_phi_prob: 0.6
  prior_psi_shape: 0.5
  beta_rho_scale: [-5, 0.1]
  bias_rho_scale: [-5, 0.1]
  weight_xi_shape: 0.3
  weight_omega_shape: 0.5

  in_channels: 1
  out_channels: 10

  loss: "ELBO"
