#### general settings
name: MCD
train_type: CLS
gpu_ids: [2]

#### datasets
data:
  name: "TinyImageNet"
  image_size: 64
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/LeNet_TinyImageNet/"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### Model settings
model:
  name: "LeNet"
  layer_type: Freq

  in_channels: 3
  out_channels: 200

#### training settings: learning rate scheme, loss, optimizer
train:

  num_epochs: 1000
  batch_size: 128
  train_size: 1

  mcd: 0.2

  loss: "CE"

#### Logging
logging:
  mode: online # disabled
  tags: [
      "TinyImageNet",
      "CLS",
      "LeNet",
      "MCD"
    ]