#### general settings
name: MFVI
train_type: CLS
gpu_ids: [2]

#### datasets
data:
  name: "CIFAR10"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/MFVIResNet_CIFAR10/"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001  # Learning rate
  weight_decay: 0.001

#### Model settings
model:
  name: "ResNet101"
  layer_type: "MFVI"

  prior:
    prior_mu: 0
    prior_sigma: 0.01
    posterior_mu_initial: [0, 0.01]
    posterior_rho_initial: [-3, 0.01]


  in_channels: 3
  out_channels: 10

#### training settings: learning rate scheme, loss, optimizer
train:

  num_epochs: 200
  batch_size: 1024
  train_size: 1

  beta: 0.00001

#### Logging
logging:
  mode: online # disabled
  tags: [
      "CIFAR10",
      "CLS",
      "ResNet101",
      "MFVI"
    ]